name: Manage VPN Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: deploy, start, stop, or destroy'
        required: true
        default: 'deploy'
        options:
          - deploy
          - start
          - stop
          - destroy
      stack:
        description: 'Pulumi stack to use (e.g., dev, staging, production)'
        required: true
        default: 'dev'

jobs:
  manage-vpn:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Run Pulumi Command Based on Action
    - name: Perform Pulumi Action
      uses: pulumi/actions@v4
      with:
        command: |
          case "${{ github.event.inputs.action }}" in
            deploy)
              echo "Deploying infrastructure..."
              pulumi up --yes
              ;;
            destroy)
              echo "Destroying infrastructure..."
              pulumi destroy --yes
              ;;
            *)
              echo "Unsupported action for Pulumi."
              exit 1
              ;;
          esac
        stack-name: ${{ github.event.inputs.stack }}
        pulumi-version: ^3

    # Step 4: Additional Actions for EC2 Management
    - name: Manage EC2 Instance
      if: ${{ github.event.inputs.action == 'start' || github.event.inputs.action == 'stop' }}
      run: |
        INSTANCE_ID=$(pulumi stack output instance_public_ip | xargs -n1 aws ec2 describe-instances --filters "Name=ip-address,Values={}" --query "Reservations[0].Instances[0].InstanceId" --output text)
        if [ "${{ github.event.inputs.action }}" == "start" ]; then
          echo "Starting EC2 instance..."
          aws ec2 start-instances --instance-ids $INSTANCE_ID
        elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
          echo "Stopping EC2 instance..."
          aws ec2 stop-instances --instance-ids $INSTANCE_ID
        fi
